### ISSUE TITLE
Why are you using x-only public keys to hash? and other questions

### ISSUE THREAD

**Issue by fiatjaf** [optout21/nip41-proto0#1]
I'm trying to make my implementation be compatible with this, but this is such a complex protocol for my brain, so it would be nice to be able ask you such questions like that. Can you message me on Telegram? https://t.me/fiatjaf

Otherwise I can ask them here.

**Comment by optout21** [comment]
Message sent.

There is ExtendedPublicKey (both X and Y coordinates), PublicKey (X and parity), and XOnlyPublicKey (X only).With a given X coordinate there are two Y values that are on the curve (Y and -Y), so storing Y is kind of redundant.
I chose to use XOnlyPublicKey because the Nostr library I use uses XOnlyPublicKey for public key, which is (I think) is due to the Schnorr signatures used in Nostr.
So here I hash the 32-byte X coordinate, but you are right, the full public key could also be used. I think this needs to be specified for interoperabilty, good point!
